# Generated by Django 4.2.5 on 2023-10-03 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                ("preco", models.FloatField()),
                ("imagem", models.ImageField(upload_to="produtos/")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.categoria",
                    ),
                ),
            ],
        ),
    ]
