# Generated by Django 4.2.6 on 2023-10-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_produto_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(default=0, max_length=9999),
        ),
    ]
