# Generated by Django 4.2.3 on 2023-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0004_alter_produto_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
