# Generated by Django 4.2.7 on 2023-11-07 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0005_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
